<?php  
/*
*
* This file was initially generated by snoobix.com designer.
*
* snoobix.com is an open source project that gives you opportunity to make 
* fully functional database applications.
*
* For further enhancements and modifications according to your needs,
* Please contact us at support@snoobix.com
*
*/

if(group_access_rights($clientid, $usrid, $usrtype, $applicname, "#modulename", 'delete') != 1) {
	$_SESSION['error']="Insufficient Privileges";
	//header('Location: ' . $_SERVER['HTTP_REFERER']); exit;
}
  
	$count=count($_POST['eid']);
	for ($i=0; $i < $count; $i++) { 
		$sqldel = "delete from #tablename where id = '".intval($_POST['eid'][$i])."'";
		mysqli_query($dbcon, $sqldel);
	}	

	//$str=($_SERVER['QUERY_STRING']<>"")?"?".$_SERVER['QUERY_STRING']:"";
	$insertGoTo = '#pagename';
	header(sprintf("Location: %s", 'modl.php?scrn='.$insertGoTo));exit;

?>