<?php 
/*
*
* This file was initially generated by snoobix.com designer.
*
* snoobix.com is an open source project that gives you opportunity to make 
* fully functional database applications.
*
* For further enhancements and modifications according to your needs,
* Please contact us at support@snoobix.com
*
*/
if(group_access_rights($clientid, $usrid, $usrtype, $applicname, "#modulename", 'view') != 1) {
	$_SESSION['error']="Insufficient Privileges";
	//header('Location: ' . $_SERVER['HTTP_REFERER']); exit;
}

$eid = $_GET['eid'];

$formname = "#pagename";

if (isset($_POST['actions']) && $_POST['actions']!='')
{
	 $actions=$_POST['actions'];
	 
	 $eid=$_POST["eid"];
	$totalrecords=count($eid);
	$counter=0;	
	while ($counter < $totalrecords)
	{
		if ($actions=='Y')
			 $query="update  #tablename  set active='Y' WHERE id=$eid[$counter]";
			 
		else if ($actions=='N')
			 $query="update  #tablename   set  active='N' WHERE id=$eid[$counter]";
			 
		//echo $query;	 die(); 
		mysqli_query($dbcon, $query);
		$counter++;
	}
}

?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">

<!--[if lt IE 7]> <html class="ie lt-ie9 lt-ie8 lt-ie7 fluid sticky-sidebar sidebar"> <![endif]-->
<!--[if IE 7]>    <html class="ie lt-ie9 lt-ie8 fluid sticky-top sticky-sidebar sidebar"> <![endif]-->
<!--[if IE 8]>    <html class="ie lt-ie9 fluid sticky-top sticky-sidebar sidebar"> <![endif]-->
<!--[if gt IE 8]> <html class="ie gt-ie8 fluid sticky-top sticky-sidebar sidebar"> <![endif]-->
<!--[if !IE]><!-->
<html class="fluid sticky-top sticky-sidebar sidebar" xmlns="http://www.w3.org/1999/xhtml"><!-- <![endif]-->

<head>
<?php include('header.php'); ?>

<script>

function getXMLHTTP() { //fuction to return the xml http object
		var xmlhttp=false;	
		try{
			xmlhttp=new XMLHttpRequest();
		}
		catch(e)	{		
			try{			
				xmlhttp= new ActiveXObject("Microsoft.XMLHTTP");
			}
			catch(e){
				try{
				xmlhttp = new ActiveXObject("Msxml2.XMLHTTP");
				}
				catch(e1){
					xmlhttp=false;
				}
			}
		}
		 	
		return xmlhttp;
	}

	
function getlovdetail(){
 //alert('function getlovdetail() is called');
 /*var req = getXMLHTTP();		
	if (req) {			
		
		var lovid = document.getElementById('lovid').value;
		var dataString = 'lovid='+lovid;
		//alert("data string: "+dataString);
		req.onreadystatechange = function() {
			if (req.readyState == 4) {
				// only if "OK"
				if (req.status == 200) {						
					document.getElementById('divlovdetails').innerHTML=req.responseText;						
				} else {
					alert("There was a problem while using XMLHTTP:\n" + req.statusText);
				}
			}				
		}			
		req.open("GET","ajax_lov.php?"+dataString, true);
		req.send(null);
	}
	//getShape(strURL);	
	//getMaxcarat(strURL);
	*/
	
	var vlovid = document.getElementById('lovid').value;
	window.location = "lovs.php?mid="+vlovid;
}

function popup_view(recid){
	sList = window.open("modl.php?scrn=#viewpagename&id="+recid, "list", "width=950,height=600,toolbar=no,scrollbars=yes,resizable=yes");
}

</script>	

<script language="javascript" type="text/javascript">
function record_update(kk)
{
	var bOK; 
	var selItems=0; 
	selItems=SelectedItems(); 
	if (selItems==0) 
		alert("Select First!");
	else  
	{  

		if (kk=='Y') bOK = confirm("Are you sure you want to activate selected.?"); 
		if (kk=='N') bOK = confirm("Are you sure you want to deactivate selected.?"); 
			
			if(bOK) 
			{ 
				document.frm.actions.value=kk;
				document.frm.action="";
				document.frm.submit();
			}
	}
}
function fnBgColor(dd, pp) {
	if(document.frm.eid[dd].checked==true)
	{
		var ii=document.getElementById(pp);
		
		ii.style.background="#FCFC01";
	} else {
		var ii=document.getElementById(pp);
		
		ii.style.background="#999999";
	}	
}
function iBgColor(dd, pp) {
	if(document.frm.intimation[dd].checked==true)
	{
		var ii=document.getElementById(pp);
		
		ii.style.background="#CCCCCC";
	} else {
		var ii=document.getElementById(pp);
		
		ii.style.background="#E8E8E8";
	}	
}
function SelectedItems() 
{ 
	var count=0; 
	var i=0; 
	var selItems=0; 
	var count=document.frm.eid.length; 
	if (count>1) 
	{
		for(i=0; i<count; i++) 
		{ 
			if (document.frm.eid[i].checked==true) 
			{	
				selItems=selItems+1;				
			}
		} 
	}
	else 
	{ 
		if (document.frm.eid.checked==true)
		{
			selItems=selItems+1; 
		}
	} 
 return selItems;
}  


function  record_add()
{
		//var vlovid = document.frm.lovid.value;
		document.frm.action="#addfilelink";
		//document.frm.lang.value=lang;
		document.frm.submit();
}

	
function  record_edit()
{
	var bOK; 
	var selItems=0; 
	selItems=SelectedItems(); 
	if (selItems==0) 
		alert("Select First!");
	else
		if (selItems > 1) 
			alert("Select one only"); 
		else 
		{
			document.frm.action="#editfilelink";
			document.frm.submit();
		}
return false;
}


	
function  record_duplicate(){
	var bOK; 
	var selItems=0; 
	selItems=SelectedItems(); 
	if (selItems==0) 
		alert("Select First!");
	else
		if (selItems > 1) 
			alert("Select one only"); 
		else 
		{
			document.frm.action="#duplicatefilelink";
			document.frm.submit();
		}
return false;
}

function  record_delete(){
	var bOK; 
	var selItems=0; 
	selItems=SelectedItems(); 
	if (selItems==0) 
		alert("Select First!");
	else 
	{  
	
		bOK = confirm("Are you sure to delete this record?"); 
		if(bOK) 
		{ 
			//alert('mid = '+mid);
			document.frm.action="#deletefilelink";
			document.frm.submit();
		}
	}
}


function ckall(){
	var count=0; 
 	var a=0; 
	 count=document.frm.eid.length; 
	// alert(count);
	for(a=0;a<count;a++)
	{
	var bb="eid"+a;
		if (document.frm.eid[0].checked==false) 
		{
			document.frm.eid[a].checked=false;
			$("#uniform-eid span").removeClass("checked");
			if (a>0)  fnBgColor (a, bb);
		}
		else if(document.frm.eid[0].checked==true)
		{
		document.frm.eid[a].checked=true;
		$("#uniform-eid span").addClass("checked");
		if (a>0)  fnBgColor (a, bb);
		}
	}
}

</script>

</head>


<body class="">

		<!-- Main Container Fluid -->
	<div class="container-fluid fluid menu-left">
		
				<!-- Sidebar menu & content wrapper -->
		<div id="wrapper">
		
		<?php include('sidebar.php'); ?>		
		<?php include('topmenu.php'); ?>
		
	<ul class="breadcrumb">
	<li>You are here</li>
	<li><a href="modl.php?scrn=dashboard.php" class="glyphicons dashboard"><i></i> <?php echo TITLE; ?></a></li>
	<li class="divider"></li>
	<li><?php echo APPLICATIONAME; ?></li>	<li class="divider"></li>
	<li>#modulename - List</li>
</ul>

<!-- Heading -->
<div class="heading-buttons">
	<h3>#modulename - List</h3>

	<div class="buttons pull-right">
		<?php if(filexists($applicname,str_replace('modl.php?scrn=','','#addfilelink'))){ ?>
			<a style="cursor:pointer;" class="btn btn-primary btn-icon glyphicons circle_plus" onClick="javascript:record_add();" ><i></i> Add</a>
		<?php } ?>
		<?php if(filexists($applicname,str_replace('modl.php?scrn=','','#editfilelink'))){ ?>
			<a style="cursor:pointer;" class="btn btn-primary btn-icon glyphicons pen" onClick="javascript:record_edit();" ><i></i> Edit </a>
		<?php } ?>
		<?php if(filexists($applicname,str_replace('modl.php?scrn=','','#duplicatefilelink'))){ ?>
			<a style="cursor:pointer;" class="btn btn-primary btn-icon glyphicons more_items" onClick="javascript:record_duplicate();" ><i></i> Duplicate </a>
		<?php } ?>
		<?php if(filexists($applicname,str_replace('modl.php?scrn=','','#deletefilelink'))){ ?>
			<a style="cursor:pointer;" class="btn btn-primary btn-icon glyphicons circle_remove" onClick="javascript:record_delete();" ><i></i> Delete </a>
		<?php } ?>
		
		<a style="cursor:pointer;" class="btn btn-primary btn-icon glyphicons ok" onClick="javascript:record_update('Y');"><i></i> Activate </a>
		<a style="cursor:pointer;" class="btn btn-primary btn-icon glyphicons ban" onClick="javascript:record_update('N');"><i></i> Deactivate </a>
	</div>
	<div class="clearfix"></div>
</div>
<div class="separator bottom"></div>
<!-- // Heading END -->
	
<div class="innerLR">
	<form action="" method="post" name="frm" id="frm">
			
	<!-- Widget -->
	<div class="widget widget-heading-simple widget-body-gray">
		<div class="widget-body">
			<div id="divlovdetails">
			<!-- Table -->
			<!--table class="dynamicTable tableTools table table-striped table-bordered table-condensed table-white"-->
			<!--table class="table table-bordered table-condensed table-striped table-primary table-vertical-center checkboxs"-->
			<table class="colVis table table-striped table-bordered table-condensed table-white">
				<!-- Table heading -->
				<thead>
					<tr>
						<th><input name='ckall' id='ckall' type="checkbox"></th>
						<th>Seq.</th>
						#listpage_headings
						<th>Active</th>
						
					</tr>
				</thead>
				<!-- // Table heading END -->
				
				<!-- Table body -->
				<tbody>
				
				<?php
					$sql = "select #listpage_fields from #tablename where 1 ";
					$filter_cond =  get_filter_condition($usrid,'#tablename');
					if($filter_cond != false){
						$sql .= " and ( ".$filter_cond." ) ";
					}
					///echo $sqlpagedetail ;
					$res = mysqli_query($dbcon, $sql);
					$cntr=0;
					while($row = mysqli_fetch_assoc($res)){
					$cntr++;
				?>				 
				
					<!-- Table row -->
					<tr class="gradeX">
						<td><input name="eid[]" id="eid" type="checkbox" value="<?php echo $row['id']; ?>" onClick="fnBgColor(<?php echo $cntr?>,'eid<?php echo $cntr;?>');"></td>
						<td><?php echo $cntr; ?></td>
						
						#listpage_values
						
						<td class="center"><?php echo $row['active']; ?></td>
					</tr>
					<!-- // Table row END -->
				
				<?php
					}
				?>

				</tbody>
				<!-- // Table body END -->
				
			</table>
			<!-- // Table END -->
			</div>
		</div>
	</div>
	<input type="hidden" name="actions" id="actions" value="" />
	</form>
	<!-- // Widget END -->
	
		</div>
		<!-- // Content END -->
		
				</div>
		
		<!-- // Sidebar menu & content wrapper END -->
				
		
		<!-- // Footer END -->
		
	</div>
	<!-- // Main Container Fluid END -->
	
<?php include('themer.php'); ?>
</body>
</html>